spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ordernest
    username: ordernest
    password: ordernest
    hikari:
      connection-init-sql: SET TimeZone='UTC'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: WSpsKRNtCdb99hofVJiC0X8ji4esmd3AyYpGTew1dJK1jiPDniDkD+aMEYd01XmIwyXeuJL9hENQK5liWllLWQ==
  expiration: 86400000